// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8d6uHyupv7BnoOR5V8PztebFgAmjVio',
    appId: '1:575134766635:web:b9ebfeb740247a900bbc6e',
    messagingSenderId: '575134766635',
    projectId: 'hw04-d6696',
    authDomain: 'hw04-d6696.firebaseapp.com',
    storageBucket: 'hw04-d6696.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO8QUSt3dxW4VsgQfgJp_1ZVqyJPTB5UY',
    appId: '1:575134766635:android:ee432c6ce3adbd4d0bbc6e',
    messagingSenderId: '575134766635',
    projectId: 'hw04-d6696',
    storageBucket: 'hw04-d6696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6a4oFLGI6HBBxy1Kiph2YhLeVSmFl80',
    appId: '1:575134766635:ios:552b2766ec8671f90bbc6e',
    messagingSenderId: '575134766635',
    projectId: 'hw04-d6696',
    storageBucket: 'hw04-d6696.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD6a4oFLGI6HBBxy1Kiph2YhLeVSmFl80',
    appId: '1:575134766635:ios:552b2766ec8671f90bbc6e',
    messagingSenderId: '575134766635',
    projectId: 'hw04-d6696',
    storageBucket: 'hw04-d6696.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM8d6uHyupv7BnoOR5V8PztebFgAmjVio',
    appId: '1:575134766635:web:975c251f780d59e00bbc6e',
    messagingSenderId: '575134766635',
    projectId: 'hw04-d6696',
    authDomain: 'hw04-d6696.firebaseapp.com',
    storageBucket: 'hw04-d6696.firebasestorage.app',
  );
}
